config/routes.rb
Rails.application.routes.draw do
 resources :posts, only: [:index, :new, :create, :show]
 root 'top#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all

  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to "/"

  end

  def show
    @post = Post.find(params[:id])
  end

private
def post_params
params.permit(:genre, :title, :text)
  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @posts = Post.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReviewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<%= link_to "トップ", "/" %>
<% @posts.each do |post| %>
<p><%= post.id  %>
<%= post.title %><br>
<%= post.text %></p>
<% end %>

app/views/posts/new.html.erb
<%= link_to "トップ", "/" %>
<%= form_tag('/posts', method: :post) do %>
<input type="text" name="genre">
<input type="text" name="title">
<textarea cols="30" type="text" name="text" rows="10"></textarea>
  <input type="submit" value="SENT">
  <% end %>

app/views/posts/show.html.erb
<%= @post.genre %>
<%= @post.title %>
<%= @post.text %>

app/views/posts/untitled.html.erb
<%= form_for(@post) do |f| %>
<%= f.label :ジャンルを入力してください %><br />
<%= f.text_field :genre %><br />
<%= f.label :タイトルを入力してください %><br />
<%= f.text_field :title %><br />
<%= f.label :感想を入力してください %><br />
<%= f.text_area :text %>
<%= f.submit "送信する" %>
<% end %>

app/views/top/index.html.erb
<p>
  レビュー数:<%= @posts.count %>
  <%= link_to "レビューを書く", new_post_path %>
  <%= link_to "レビューを見る", posts_path %>
</p>